### ISSUE TITLE
Cannot read property 'Tag' of undefined.

### ISSUE THREAD

**Issue by peterswallow** [fb55/domhandler#575]
I have a react.js project, which indirectly uses `domhandler` v4.2.0 via`cheerio` I believe.

Its worked fine for months and then suddenly, my project has started throwing this error when I try to build it.

```
C:\product-app\node_modules\domhandler\lib\node.js:32
    [domelementtype_1.ElementType.Tag, 1],
                                  ^

TypeError: Cannot read property 'Tag' of undefined
    at Object.<anonymous> (C:\product-app\node_modules\domhandler\lib\node.js:32:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\product-app\node_modules\domhandler\lib\index.js:15:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

Any ideas what might be causing it? 

I'm running node.js 12.16.1 with typescript 3.9.10.

**Comment by markwoon** [comment]
I'm using `react-html-parser` which has a dependency on `domhandler`.  I'm seeing this error as well after `react-html-parser` updated from `domhandler` 4.0 to 4.2.

**Comment by fb55** [comment]
This seems to me like you are using an outdated version of `domelementtype`. Could you try deleting your node_modules and package lock file and reinstalling / alternatively explicitly installing the latest version of that package?

**Comment by markwoon** [comment]
That did the trick.  Thanks.

**Comment by fb55** [comment]
Thanks for confirming @markwoon! Assuming this is resolved.
